apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-mcr
  name: nginx-mcr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-mcr
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-mcr
    spec:
      containers:
      - image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
        imagePullPolicy: Always
        name: nginx-mcr
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always